services:
  backstage-postgres:
    image: postgres:16-alpine
    ports:
      - 5444:5432
    volumes:
      - ~/apps/postgres-backstage:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${BACKSTAGE_DB_PASSWORD}
      - POSTGRES_USER=backstage_user
      - POSTGRES_DB=backstage